android/build.gradle

This allows easy upgrading when a new React Native version is out or when the Android SDK version is changed.

Use Android root project settings

---

RNReactNativeHapticFeedback.podspec

Creates a duplicate react in the project

React doesn't need to be in the podspec (depricated)

---

react-native-haptic-feedback.podspec

Our project includes react native modules via `pod 'react-native-haptic-feedback', :path => 'node_modules/react-native-haptic-feedback’`
Because of the mismatch in names between the project and the .podspec, this was not possible
I have renamed the .podspec file and further made explicit the dependency on React

Enable react-native-haptic-feedback to be included in Podfile 

---

ios/RNReactNativeHapticFeedback.m

Lib mistakenly treats iPhone SE as a device with haptic feedback support.

Exclude iPhone SE from supported devices

---

ios/RNReactNativeHapticFeedback.m

Hey @mkuczera! Thank you for the library!
While testing it, I have encountered that it didn't work for iPhone 6S and 6S Plus, due to weak taptic engine that doesn't support all possible variants that work for >= iPhone 7. So I have added haptic feedback for some of the variants such as `selection`, `impactMedium` and `notificationWarning`.
This article have lead me to this -> https://medium.com/@sdrzn/make-your-ios-app-feel-better-a-comprehensive-guide-over-taptic-engine-and-haptic-feedback-724dec425f10

Make it work for iPhone 6S and iPhone 6S Plus

---

README.md
android/src/main/java/com/mkuczera/RNReactNativeHapticFeedbackModule.java
index.d.ts
index.js
ios/RNReactNativeHapticFeedback.m

Haptic feedback triggers despite the user's system settings. (If they turn off haptic via the accessibility settings then haptic does disable).
The change checks the haptic system settings prior to triggering and will return if haptic is disabled.

check haptic system settings before triggering

---

index.js

The current version results in errors when loading with metro bundler because of the syntax.

Use ES6 syntax

---

index.js

Android will throw a `com.facebook.react.bridge.NoSuchKeyException` when using the old trigger arguments after the latest update.
Looks as though I forgot to test this scenario properly with #28

com.facebook.react.bridge.NoSuchKeyException

---

README.md

Fixed the formatting in Readme that was causing unescaped code to be hidden in preview.

Fixed some MD formatting in Readme

---

ios/RNReactNativeHapticFeedback.m

Resolves #42 
This increases performance on iOS in two ways:
* Re-uses generators, lazy-loads them.  Initializing generators is expensive and slow; this change makes scrubbing through a list with feedback feel way more natural.
* Prepare after call.  Best practice is to trigger the feedback first, then call prepare to get ready for the next one.  Calling prepare before each time slightly delays the actual haptics from playing.
I use `impactLight` in my app and can call it 20-30 times in 1 second.  This change made a huge difference, changing it from stuttering haptic feedback to smooth and consistent.

Updating iOS to cache generators (lazy-load) for better performance

---

package.json

With the major react-native release (v 0.60), it's recommended to give support for specific versions.

Update react-native version to support only 0.60 and up versions.

---

package.json

When installing this library, yarn currently gives the following warning (I'm using `react-native@~0.63.2`):
```
warning " > react-native-haptic-feedback@1.10.0" has incorrect peer dependency "react-native@^0.60.0"
```
This PR loosens the react-native peer dependency version requirement and should eliminate the warning.

Loosen react-native peer dependency version

---

RNReactNativeHapticFeedback.podspec

Latest Xcode 12 fails to build while without a module to depend on React-Core directly hence this change is necessary for all native modules on iOS. For more details please check: https://github.com/facebook/react-native/issues/29633#issuecomment-694187116

fix: Xcode 12 compatibility

---

ios/RNReactNativeHapticFeedback.h

The `<` import (module maps) fixes duplicate symbol errors on RN 0.67.

fix: Fix duplicate symbol definition build error (ObjC `<` import)

---

index.d.ts

With the current declaration, `trigger` can be imported from the destructured import
```ts
import { trigger } from 'react-native-haptic-feedback';
```
However, the function does not exist in the source code. This PR fixes this issue and only return `trigger` when used with the class `ReactNativeHapticFeedback.trigger(...)` declaration

fix: class declaration

---

ios/RNReactNativeHapticFeedback.h

Expo 44.0 now requires importing RN headers using `#import <React/*.h>` form, see https://github.com/expo/expo/issues/15622#issuecomment-997141629 . Old import style will cause the following build errors.
```
Showing Recent Messages
CompileC /Users/abing/Library/Developer/Xcode/DerivedData/GcoresMobile-gakxkwdaeaesajbslhafuviqcirt/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/RNReactNativeHapticFeedback.build/Objects-normal/arm64/RNReactNativeHapticFeedback.o /Users/abing/Code/gcores/gcores-mobile/node_modules/react-native-haptic-feedback/ios/RNReactNativeHapticFeedback.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'RNReactNativeHapticFeedback' from project 'Pods')
cd /Users/abing/Code/gcores/gcores-mobile/ios/Pods
export LANG\=en_US.US-ASCII …
```

fix: change header import style to work with latest Expo SDK

---

.npmignore

@mkuczera could you please restore `src` folder to npm package and release new version with it? This folder is needed in order for codegen to work correctly since it looks for this folder while parsing specs. Also, what is the reason for not including it anyways?

fix: add src folder to npm in order to make codegen work

---

RNReactNativeHapticFeedback.podspec

Fixing error `'value' is unavailable: introduced in iOS 12.0`
Issue related to 14.3 version of Xcode and new arch enabled  
Issue - https://github.com/mkuczera/react-native-haptic-feedback/issues/100

FIX: iOS build issues with new architecture 

---

android/src/main/java/com/mkuczera/RNReactNativeHapticFeedbackModuleImpl.java
android/src/main/java/com/mkuczera/RNReactNativeHapticFeedbackPackage.java
android/src/main/java/com/mkuczera/vibrateFactory/Vibrate.java
android/src/main/java/com/mkuczera/vibrateFactory/VibrateFactory.java
android/src/main/java/com/mkuczera/vibrateFactory/VibrateWithCreatePredefined.java
android/src/main/java/com/mkuczera/vibrateFactory/VibrateWithDuration.java
android/src/main/java/com/mkuczera/vibrateFactory/VibrateWithHapticConstant.java

During an analysis of the `react-native-haptic-feedback` library using the Android Analyzer, a discrepancy was identified between the package declaration and the corresponding directory structure. The error flagged was:
```
Package name 'com.mkuczera' does not correspond to the file path 'com.mkuczera.VibrateFactory'
```
This mismatch not only confuses code readers but also potentially disrupts some tools from working correctly. Such an inconsistency, although not strictly mandated by the Java language, is important to address to ensure consistency and optimal functionality across various toolchains and IDEs.
To address the highlighted inconsistency:
1. **Package Name Update**: I changed the package name from `com.mkuczera` to `com.mkuczera.vibrateFactory` to better align with the class's …

Refactor: Align Package Name with Directory Structure for vibrateFactory

---

android/src/main/java/com/mkuczera/RNReactNativeHapticFeedbackModuleImpl.java

There seems to be a problem with the `ignoreAndroidSystemSettings `option. Many people have no haptic response when the `ignoreAndroidSystemSettings `option is set to `false`, so they are using it with it set to `true`.  (https://github.com/mkuczera/react-native-haptic-feedback/issues/97)
The previously used `Settings.System.HAPTIC_FEEDBACK_ENABLED` option has been deprecated and no longer returns the enabled state of haptic. Because it simply returns a string called `haptic_feedback_enabled`, hapticEnabledAndroidSystemSettings always has to be `0`.
https://developer.android.com/reference/android/provider/Settings.System#HAPTIC_FEEDBACK_ENABLED
So I propose a new vibration enable condition.
The first is when the device has a vibration function.
The second is when the user turns on the …

Fix Android Vibration enable condition

---

src/NativeHapticFeedback.ts
src/index.ts

Modified the method parameter type from a generic string to a stricter type definition.
This stricter type definition allows developers to intuitively understand available methods without referring to external documentation.
As a result, this enhances code readability, improves DX, and minimizes the chances of bugs due to incorrect method invocations.
as-is:
to-be:

feat: strict type on the trigger func argument

---

RNReactNativeHapticFeedback.podspec

Similar to e.g. https://github.com/software-mansion/react-native-svg/blob/979fb06b131c5280cc5be6325ce3bc264e29fe49/RNSVG.podspec#L24, we wan to utilize `install_modules_dependencies` method when it is already available (and it is from RN `0.71`). It also is required from RN `0.75` to even compile the project on new arch.

fix: align with 0.75

---

RNReactNativeHapticFeedback.podspec

if you use an old tag, the latest native files get pulled. With this fix, the native files will match the installed version

use right version in podspec

---

src/NativeHapticFeedback.ts

Codegen does not support Union Types and Enums. 
Closes #127 #128 
You should be able to install the dependencies

fix: use string instead of enum type to avoid codegen fails

---

src/index.ts

Export types from `types.ts`
They were mistakenly removed during https://github.com/mkuczera/react-native-haptic-feedback/pull/135
https://github.com/mkuczera/react-native-haptic-feedback/pull/135#discussion_r1764975005
@mkuczera Would be great to get a patch version

fix: export types from index
